spring.application.name=user-service
server.port=9020

jwt.SecretKey=dfcgvhbfghjklertyuiocecieccjjeivvbvvownijbvivdipifnif75kkk3fv64v6vws

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=your_username
spring.datasource.password=your_secure_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
