spring.application.name=posts-service
server.port=9030
#Db configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/linkedInApp
spring.datasource.username=your_username
spring.datasource.password=your_secure_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
